/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JogoRPG;

import Ferramentas.Arquivo;
import Ferramentas.Globais;

/**
 *
 * @author mari
 */
public class TelaTentar extends javax.swing.JFrame {
Arquivo objArquivo;
int vetN [] = new int [5];
    /**
     * Creates new form TelaTentar
     */
    public TelaTentar() {
        initComponents();
        Globais.ajustarImagem(getClass().getResource("/imagens/LugarAbandonado.png"), lblLy);
        lblTexto.setText("<html> Você errou a questão, infelizmente com o seu desgaste"
                + " você perdeu -10 de vida, porém pode tentar novamente..."
                + " Se responder corretamente ganha +10 de poder para compater o inimigo, mas se"
                + " errar  perde novamente +10 de vida!<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTN = new javax.swing.JButton();
        btnSeguir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        lblLy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTN.setBackground(new java.awt.Color(102, 102, 0));
        btnTN.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        btnTN.setForeground(new java.awt.Color(255, 255, 255));
        btnTN.setText("Tentar outra vez");
        btnTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTNActionPerformed(evt);
            }
        });
        getContentPane().add(btnTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        btnSeguir.setBackground(new java.awt.Color(102, 102, 0));
        btnSeguir.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        btnSeguir.setForeground(new java.awt.Color(255, 255, 255));
        btnSeguir.setText("Seguir mesmo assim");
        btnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 0)));

        lblTexto.setBackground(new java.awt.Color(204, 204, 204));
        lblTexto.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblLy.setText("jLabel1");
        getContentPane().add(lblLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 417, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTNActionPerformed
        Globais.exibirMensagem("<html>Escolha sábia! Agora você só precisa acertar a questão para ganhar mais poder...<br>"
                + "Boa Sorte!</html>");
        
        TelaQ1 tela1 = new TelaQ1();
       tela1.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnTNActionPerformed

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
     
      Globais.exibirMensagem("<html> Escolha arriscada! Talvez você esteja subertimando o inimigo,"
               + " tenha cuidado...</html>");
       objArquivo  = new Arquivo("nivel.txt");
            objArquivo.abrirLeitura();
            String linha2 = objArquivo.lerLinha();
            objArquivo.fecharArquivo();
            switch (linha2) {
                case "":
                    new TelaCombate1().setVisible(true);
                    dispose();
                    break;
                case "Nivel2":
                    new TelaCombate2().setVisible(true);
                    dispose();
                    break;
                case "Nivel3":
                    new TelaCombate3().setVisible(true);
                    dispose();
                    break;
                case "Nivel4":
                    new TelaCombate4().setVisible(true);
                    dispose();
                    break;
                case "Nivel5":
                    new TelaCombate5().setVisible(true);
                    dispose();
                    break;
                default:
                    break;
            }


    }//GEN-LAST:event_btnSeguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTentar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeguir;
    private javax.swing.JButton btnTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLy;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
