/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JogoRPG;

import Ferramentas.Arquivo;
import Ferramentas.Globais;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author mari
 */
public class TelaEPersonagens extends javax.swing.JFrame {
    
    Personagens objP1 = new Personagens("Marie Curie", "Radiação", 70, 40);
    Personagens objP2 = new Personagens("Nikola Tesla", "Eletricidade", 90,20 );
    Personagens objP3 = new Personagens("Charles Darwin", "Transformação", 100, 10);
    Personagens objP4 = new Personagens("Albert Einstein", "Relatividade", 80, 30);
    Personagens objP5 = new Personagens("Ada Lovelace", "Lógica", 90, 20);
    Personagens objP6 = new Personagens("Sigmund Freud", "Controle da mente", 80, 30);
    Arquivo objArquivo;
    
    @SuppressWarnings("empty-statement")
    public TelaEPersonagens() {
        initComponents();
        
        Globais.ajustarImagem(getClass().getResource("/imagens/LugarAbandonado.png"), lblLy);
         Globais.ajustarImagem(getClass().getResource("/imagens/MarieCurie.png"), lblMC);
         Globais.ajustarImagem(getClass().getResource("/imagens/NikolaTesla.png"), lblTesla);
         Globais.ajustarImagem(getClass().getResource("/imagens/CharlesDarwin.png"), lblDarwin);
        Globais.ajustarImagem(getClass().getResource("/imagens/AlbertEinstein.png"), lblAE);
        Globais.ajustarImagem(getClass().getResource("/imagens/AdaLovelace.png"), lblAda);
        Globais.ajustarImagem(getClass().getResource("/imagens/freud.png"), lblF);
        selecionado(lblTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblMC = new javax.swing.JLabel();
        lblTesla = new javax.swing.JLabel();
        lblDarwin = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblAda = new javax.swing.JLabel();
        lblAE = new javax.swing.JLabel();
        btnAvançar = new javax.swing.JButton();
        pnAtributos = new javax.swing.JPanel();
        lblAtributos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLy = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMC.setText("Marie Curie");
        lblMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMCMouseClicked(evt);
            }
        });

        lblTesla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTesla.setText("Tesla");
        lblTesla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTeslaMouseClicked(evt);
            }
        });

        lblDarwin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDarwin.setText("Darwin");
        lblDarwin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDarwinMouseClicked(evt);
            }
        });

        lblF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblF.setText("Sigmund Freud");
        lblF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFMouseClicked(evt);
            }
        });

        lblAda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAda.setText("Ada");
        lblAda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdaMouseClicked(evt);
            }
        });

        lblAE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAE.setText("Albert Einstein");
        lblAE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMC, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTesla, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDarwin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTesla, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDarwin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAE, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnAvançar.setBackground(new java.awt.Color(102, 102, 0));
        btnAvançar.setFont(new java.awt.Font("Laksaman", 1, 15)); // NOI18N
        btnAvançar.setText("Começar");
        btnAvançar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvançarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvançar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        pnAtributos.setBackground(new java.awt.Color(51, 51, 0));
        pnAtributos.setForeground(new java.awt.Color(51, 51, 0));

        lblAtributos.setFont(new java.awt.Font("Laksaman", 1, 15)); // NOI18N
        lblAtributos.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnAtributosLayout = new javax.swing.GroupLayout(pnAtributos);
        pnAtributos.setLayout(pnAtributosLayout);
        pnAtributosLayout.setHorizontalGroup(
            pnAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAtributosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnAtributosLayout.setVerticalGroup(
            pnAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAtributosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(pnAtributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 0));

        lblTitle.setBackground(new java.awt.Color(153, 153, 0));
        lblTitle.setFont(new java.awt.Font("Laksaman", 1, 15)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Escolha seu personagem:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        getContentPane().add(lblLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 670, 549));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMCMouseClicked
        lblTitle.setText("Marie Curie");
        lblAtributos.setText(objP1.toString());
        selecionado(lblTitle);
    }//GEN-LAST:event_lblMCMouseClicked

    private void lblTeslaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTeslaMouseClicked
        lblTitle.setText("Nikola Tesla");
        lblAtributos.setText(objP2.toString());
        selecionado(lblTitle);
    }//GEN-LAST:event_lblTeslaMouseClicked

    private void lblAEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAEMouseClicked
        lblTitle.setText("Albert Einstein");
        lblAtributos.setText(objP4.toString());
        selecionado(lblTitle);
    }//GEN-LAST:event_lblAEMouseClicked

    private void lblAdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdaMouseClicked
        lblTitle.setText("Ada Lovelace");
        lblAtributos.setText(objP5.toString());
        selecionado(lblTitle);
    }//GEN-LAST:event_lblAdaMouseClicked

    private void lblFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFMouseClicked
        lblTitle.setText("Sigmund Freud");
        lblAtributos.setText(objP6.toString());
        selecionado(lblTitle);
    }//GEN-LAST:event_lblFMouseClicked

    private void btnAvançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvançarActionPerformed
       try{
        if (!selecionado(lblTitle).equals("null")) {
            String result = selecionado(lblTitle);
            objArquivo = new Arquivo("Personagem.txt");
            objArquivo.abrirEscrita();
            String linha = "";
            linha = result;
            objArquivo.escreverLinha(linha);
            objArquivo.fecharArquivo();
            
            TelaNivel1 tela5 = new TelaNivel1();
            tela5.setVisible(true);
            dispose();
        
        }
       }catch(Exception ex){
          Globais.exibirMensagem("Você precisa selecionar um personagem para avançar!");
       }
    }//GEN-LAST:event_btnAvançarActionPerformed

    private void lblDarwinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDarwinMouseClicked
        lblTitle.setText("Charles Darwin");
        lblAtributos.setText(objP3.toString());
    }//GEN-LAST:event_lblDarwinMouseClicked
    
    private static String selecionado(JLabel label) {
        if (label.getText().equals("Marie Curie")) {
            return "Marie Curie";
        } else if (label.getText().equals("Nikola Tesla")) {
            return "Nikola Tesla";
        } else if (label.getText().equals("Charles Darwin")) {
            return "Charles Darwin";
        } else if (label.getText().equals("Albert Einstein")) {
            return "Albert Einstein";
        } else if (label.getText().equals("Ada Lovelace")) {
            return "Ada Lovelace";
        } else if (label.getText().equals("Sigmund Freud")) {
            return "Sigmund Freud";
        } else {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEPersonagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAE;
    private javax.swing.JLabel lblAda;
    private javax.swing.JLabel lblAtributos;
    private javax.swing.JLabel lblDarwin;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblLy;
    private javax.swing.JLabel lblMC;
    private javax.swing.JLabel lblTesla;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnAtributos;
    // End of variables declaration//GEN-END:variables
}
